landingpage changes and assets folder changes
BUMETCS673/seprojects-cs673a2f24_team4 pull request #26
Opened 2024-11-02 23:11 UTC by jaindra-bu

2024-11-05 21:46 UTC, devilsbane98 requested changes
Please see the comments on the files

2024-11-05 21:46 UTC, devilsbane98 commented on code/packages/web/src/components/JobCard.tsx
No inline styles for any tags

2024-11-05 21:46 UTC, devilsbane98 commented on code/packages/web/src/pages/dashboard/dashboard_pages/applicant_job_listings/useJobListings.ts
Dummy data?

2024-11-07 16:41 UTC, jaindra-bu commented on code/packages/web/src/components/JobCard.tsx
done, changed

2024-11-07 16:41 UTC, jaindra-bu commented on code/packages/web/src/pages/dashboard/dashboard_pages/applicant_job_listings/useJobListings.ts
yes

2024-11-08 01:01 UTC, devilsbane98 approved these changes

2024-11-08 06:41 UTC, hemant1026 approved these changes

2024-11-08 06:41 UTC, merged