Removing Inline styles and created a seperate style sheet
BUMETCS673/seprojects-cs673a2f24_team4 pull request #33
Opened 2024-11-08 23:48 UTC by hemant1026

2024-11-09 00:04 UTC, faizanurfi requested changes

2024-11-09 00:04 UTC, faizanurfi commented on code/packages/web/src/pages/dashboard/dashboard_pages/profile/Profile.tsx
> +import styles from './Profile.module.css';
Rename the file to Profile.css and import like this. No need to export it as an object `styles`

`import './Profile.css';`

2024-11-09 00:04 UTC, faizanurfi commented on code/packages/web/src/pages/dashboard/dashboard_pages/profile/Profile.tsx
> +    <Box className={styles.profileContainer}>
After changing file name and updating import, change this and rest of the classNames to:

`<Box className='profileContainer'>`

2024-11-09 00:04 UTC, faizanurfi commented on code/packages/web/src/pages/dashboard/dashboard_pages/profile/Profile.tsx
> +          src="/code/packages/web/src/pages/dashboard/dashboard_pages/profile/avatar.jpg"
Avatar is not being displayed. Plus inline paths can cause errors:

Do this instead:
- Move `avatar.jpg` to `src/assets` folder
- Import img like this `import avatarSrc from 'src/assets/avatar.jpg';`
- Use that here like this `src={avatarSrc}`

2024-11-09 00:04 UTC, faizanurfi commented on code/packages/web/src/pages/dashboard/dashboard_pages/profile/avatar.jpg
Move this file to `src/assets` folder

2024-11-09 02:07 UTC, faizanurfi approved these changes

2024-11-14 22:17 UTC, devilsbane98 approved these changes

2024-11-14 22:28 UTC, merged